services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: Maximellian
      MONGO_INITDB_ROOT_PASSWORD: Youbicurti%241126
      MONGO_INITDB_DATABASE: myapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongodb_network
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/27017"]
      interval: 10s
      timeout: 5s
      retries: 10

  # MongoDB Express
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      MY_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: Maximellian
      ME_CONFIG_MONGODB_ADMINPASSWORD: Youbicurti%241126
      #ME_CONFIG_MONGODB_URL: mongodb://Maximellian:Youbicurti%241126@mongodb:27017/admin
      ME_CONFIG_BASICAUTH_USERNAME: Maximellian
      ME_CONFIG_BASICAUTH_PASSWORD: Youbicurti%241126
    ports:
      - "8081:8081"
    networks:
      - mongodb_network
    

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  mongodb_network:
    driver: bridge 